version: "3.3" 
  
services: 
  portainer: 
    image: portainer/portainer-ce 
    container_name: portainer 
    command: -H unix:///var/run/docker.sock 
    network_mode: "host"
    restart: always 
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /patch/to/data/docker/portainer:/data:rw
    security_opt:
      - no-new-privileges:true
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid

volumes: 
  portainer: 
    driver: local
